### ISSUE TITLE
HasNot<SomeComponent> filters don't work after SomeComponent is added to entities

### ISSUE THREAD

**Issue by natebot13** [flame-engine/oxygen#12]
# Current bug behaviour

HasNot filters don't work on entities that have added components during runtime.

# Expected behaviour

HasNot should filter out entities that have added the relevant component

# Steps to reproduce

Create an entity and add CompoentA to it.
Create a Query with filters `[Has<ComponentA>(), HasNot<ComponentB>()]`
Add ComponentB to the entity and observe that the Query still has the entity in its entities list.

# Analysis
The issue looks like it's due to the fact that entities are only added to systems when a component is added and removed from systems when a component is removed. But the complete opposite is true with HasNot filters, where an entity can be removed from a system when a component is added and an entity can be added to a system when a component is removed. The relevant code locations are here:
https://github.com/flame-engine/oxygen/blob/e578c8e6ed0e4b3c00261450141f4ae814502bfb/lib/src/query/query_manager.dart#L24-L44

**Comment by gokadi** [comment]
Up!

Hi! I'm facing the same issue. My env:
```
flame: ^1.2.1
flame_oxygen: ^0.1.4. <--- **oxygen-2.0.0**
```
For now I just fix it by manual checks in the code, like 
```
if (entity.get<Component>() != null) {continue;}
```
But it's way too ugly and adds additional logic to loop :-)

**Comment by spydon** [comment]
@wolfenrain

**Comment by gokadi** [comment]
Btw, I upgraded to flame 1.2 just yesterday - used 1.0 before and the issue also persisted that time - it's not something new, I just didn't have time to look through existing issues or create bugreport with good description. Thanks to @natebot13  👍
