### ISSUE TITLE
Null safety by default?

### ISSUE THREAD

**Issue by lig** [flame-engine/oxygen#4]
Hey, I see that the development just has been started and I like the idea behind the project. It looks like the project won't be GA immediately. Thus, it looks like a good idea to make it null safe from the start.

What do you think about that?

**Comment by wolfenrain** [comment]
Indeed, it was part of my internal roadmap to ensure it was null safe before we released the first version. But haven't gotten around to look into that yet.

Shouldn't be too hard to do. Was hoping to find some time this weekend to do so.

**Comment by wolfenrain** [comment]
We have just released Oxygen, null-safe as promised!

https://pub.dev/packages/oxygen
